def create_attribute_map():
    attribute_map = {}

    #Light World
    attribute_map["Master Sword Pedestal"] = ["Light World", "Lost Woods", "Northwest Hyrule"]
    attribute_map["Link's Uncle"] = ["Light World", "Central Hyrule", "Freebie", "NPC"]
    attribute_map["Secret Passage"] = ["Light World", "Central Hyrule", "Freebie"]
    attribute_map["King's Tomb"] = ["Light World", "Central Hyrule"]
    attribute_map["Floodgate Chest"] = ["Light World", "South Hyrule", "Freebie"]
    attribute_map["Link's House"] = ["Light World", "Central Hyrule", "Freebie"]
    attribute_map["Kakariko Tavern"] = ["Light World", "West Hyrule", "Kakariko", "Freebie"]
    attribute_map["Chicken House"] = ["Light World", "West Hyrule", "Kakariko", "Freebie"]
    attribute_map["Aginah's Cave"] = ["Light World", "Southwest Hyrule", "Desert", "Freebie"]
    attribute_map["Sahasrahla's Hut - Left"] = ["Light World", "East Hyrule", "Group", "Freebie"]
    attribute_map["Sahasrahla's Hut - Middle"] = ["Light World", "East Hyrule", "Group", "Freebie"]
    attribute_map["Sahasrahla's Hut - Right"] = ["Light World", "East Hyrule", "Group", "Freebie"]
    attribute_map["Kakriko Well - Top"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Kakriko Well - Left"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Kakriko Well - Middle"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Kakriko Well - Right"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Kakriko Well - Bottom"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Blind's Hideout - Top"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Blind's Hideout - Left"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Blind's Hideout - Right"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Blind's Hideout - Far Left"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Blind's Hideout - Far Right"] = ["Light World", "West Hyrule", "Kakariko", "Group", "Freebie"]
    attribute_map["Pegasus Rocks"] = ["Light World", "Central Hyrule"]
    attribute_map["Mini Moldorm Cave - Far Left"] = ["Light World", "South Hyrule", "Group", "Freebie"]
    attribute_map["Mini Moldorm Cave - Left"] = ["Light World", "South Hyrule", "Group", "Freebie"]
    attribute_map["Mini Moldorm Cave - Right"] = ["Light World", "South Hyrule", "Group", "Freebie"]
    attribute_map["Mini Moldorm Cave - Far Right"] = ["Light World", "South Hyrule", "Group", "Freebie"]
    attribute_map["Ice Rod Cave"] = ["Light World", "Southeast Hyrule", "Freebie"]
    attribute_map["Bottle Merchant"] = ["Light World", "West Hyrule", "Kakariko", "Freebie", "NPC"]
    attribute_map["Sahasrahla"] = ["Light World", "East Hyrule", "NPC", "Fetch Quest"]
    attribute_map["Magic Bat"] = ["Light World", "Central Hyrule", "Fetch Quest"]
    attribute_map["Sick Kid"] = ["Light World", "West Hyrule", "Kakariko", "NPC", "Fetch Quest"]
    attribute_map["Hobo"] = ["Light World", "Central Hyrule", "NPC"]
    attribute_map["Bombos Tablet"] = ["Light World", "Southwest Hyrule", "Desert"]
    attribute_map["King Zora"] = ["Light World", "Northeast Hyrule", "Freebie", "NPC"]
    attribute_map["Lost Woods Hideout"] = ["Light World", "Lost Woods", "Northwest Hyrule", "Freebie"]
    attribute_map["Lumberjack Tree"] = ["Light World", "Northwest Hyrule"]
    attribute_map["Cave 45"] = ["Light World", "Central Hyrule"]
    attribute_map["Graveyard Ledge"] = ["Light World", "Central Hyrule"]
    attribute_map["Checkerboard Cave"] = ["Light World", "Southwest Hyrule", "Desert"]
    attribute_map["Mini Moldorm Cave - NPC"] = ["Light World", "South Hyrule", "Group", "Freebie"]
    attribute_map["Library"] = ["Light World", "West Hyrule"]
    attribute_map["Mushroom"] = ["Light World", "Lost Woods", "Northwest Hyrule", "Freebie"]
    attribute_map["Potion Shop"] = ["Light World", "Northeast Hyrule", "Fetch Quest"]
    attribute_map["Maze Race"] = ["Light World", "West Hyrule", "Freebie"]
    attribute_map["Desert Ledge"] = ["Light World", "Southwest Hyrule", "Desert"]
    attribute_map["Lake Hylia Island"] = ["Light World", "Southeast Hyrule"]
    attribute_map["Sunken Treasure"] = ["Light World", "South Hyrule", "Freebie"]
    attribute_map["Zora's Ledge"] = ["Light World", "Northeast Hyrule"]
    attribute_map["Flute Spot"] = ["Light World", "Central Hyrule", "Fetch Quest"]
    attribute_map["Waterfall Fairy - Left"] = ["Light World", "Northeast Hyrule", "Group"]
    attribute_map["Waterfall Fairy - Right"] = ["Light World", "Northeast Hyrule", "Group"]
    attribute_map["Blacksmith"] = ["Light World", "Central Hyrule", "NPC"]
    attribute_map["Purple Chest"] = ["Light World", "Southwest Hyrule", "NPC"]

    #Hyrule Castle
    attribute_map["Sanctuary"] = ["Light World", "Central Hyrule", "Freebie"]
    attribute_map["Sewers - Secret Room - Left"] = ["Light World", "Central Hyrule", "Hyrule Castle", "Group", "Dungeon"]
    attribute_map["Sewers - Secret Room - Middle"] = ["Light World", "Central Hyrule", "Hyrule Castle", "Group", "Dungeon"]
    attribute_map["Sewers - Secret Room - Right"] = ["Light World", "Central Hyrule", "Hyrule Castle", "Group", "Dungeon"]
    attribute_map["Sewers - Dark Cross"] = ["Light World", "Central Hyrule", "Hyrule Castle", "Dungeon"]
    attribute_map["Hyrule Castle - Boomerang Chest"] = ["Light World", "Central Hyrule", "Hyrule Castle", "Freebie", "Dungeon"]
    attribute_map["Hyrule Castle - Map Chest"] = ["Light World", "Central Hyrule", "Hyrule Castle", "Freebie", "Dungeon"]
    attribute_map["Hyrule Castle - Zelda's Cell"] = ["Light World", "Central Hyrule", "Hyrule Castle", "Freebie", "Dungeon"]

    #Eastern Palace
    attribute_map["Eastern Palace - Compass Chest"] = ["Light World", "East Hyrule", "Eastern Palace", "Freebie", "Dungeon"]
    attribute_map["Eastern Palace - Big Chest"] = ["Light World", "East Hyrule", "Eastern Palace", "Dungeon"]
    attribute_map["Eastern Palace - Cannonball Chest"] = ["Light World", "East Hyrule", "Eastern Palace", "Freebie", "Dungeon"]
    attribute_map["Eastern Palace - Big Key Chest"] = ["Light World", "East Hyrule", "Eastern Palace", "Dungeon"]
    attribute_map["Eastern Palace - Map Chest"] = ["Light World", "East Hyrule", "Eastern Palace", "Freebie", "Dungeon"]
    attribute_map["Eastern Palace - Armos Knights"] = ["Light World", "East Hyrule", "Eastern Palace", "Dungeon", "Boss"]
    attribute_map["Eastern Palace - Prize"]  = ["Light World", "East Hyrule", "Eastern Palace", "Dungeon", "Prize"]

    #Desert Palace
    attribute_map["Desert Palace - Big Chest"] = ["Light World", "Southwest Hyrule", "Desert" "Desert Palace", "Dungeon"]
    attribute_map["Desert Palace - Map Chest"] = ["Light World", "Southwest Hyrule", "Desert" "Desert Palace", "Dungeon"]
    attribute_map["Desert Palace - Torch"] = ["Light World", "Southwest Hyrule", "Desert" "Desert Palace", "Dungeon"]
    attribute_map["Desert Palace - Big Key Chest"] = ["Light World", "Southwest Hyrule", "Desert" "Desert Palace", "Dungeon"]
    attribute_map["Desert Palace - Compass Chest"] = ["Light World", "Southwest Hyrule", "Desert" "Desert Palace", "Dungeon"]
    attribute_map["Desert Palace - Lanmolas'"] = ["Light World", "Southwest Hyrule", "Desert" "Desert Palace", "Dungeon", "Boss"]
    attribute_map["Desert Palace - Prize"] = ["Light World", "Southwest Hyrule", "Desert" "Desert Palace", "Dungeon", "Prize"]

    #Death Mountain
    attribute_map["Old Man"] = ["Light World", "North Hyrule", "Death Mountain", "NPC"]
    attribute_map["Spectacle Rock Cave"] = ["Light World", "North Hyrule", "Death Mountain"]
    attribute_map["Ether Tablet"] = ["Light World", "North Hyrule", "Death Mountain"]
    attribute_map["Spectacle Rock"] = ["Light World", "North Hyrule", "Death Mountain"]
    attribute_map["Spiral Cave"] = ["Light World", "North Hyrule", "Death Mountain"]
    attribute_map["Mimic Cave"] = ["Light World", "North Hyrule", "Death Mountain"]
    attribute_map["Paradox Cave Lower - Far Left"] = ["Light World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Paradox Cave Lower - Left"] = ["Light World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Paradox Cave Lower - Right"] = ["Light World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Paradox Cave Lower - Far Right"] = ["Light World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Paradox Cave Lower - Middle"] = ["Light World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Paradox Cave Upper - Left"] = ["Light World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Paradox Cave Upper - Right"] = ["Light World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Floating Island"] = ["Light World", "North Hyrule", "Death Mountain"]

    #Tower Of Hera
    attribute_map["Tower of Hera - Big Key Chest"] = ["Light World", "North Hyrule", "Death Mountain", "Tower of Hera", "Dungeon"]
    attribute_map["Tower of Hera - Basement Cage"] = ["Light World", "North Hyrule", "Death Mountain", "Tower of Hera", "Dungeon"]
    attribute_map["Tower of Hera - Map Chest"] = ["Light World", "North Hyrule", "Death Mountain", "Tower of Hera", "Dungeon"]
    attribute_map["Tower of Hera - Compass Chest"] = ["Light World", "North Hyrule", "Death Mountain", "Tower of Hera", "Dungeon"]
    attribute_map["Tower of Hera - Big Chest"] = ["Light World", "North Hyrule", "Death Mountain", "Tower of Hera", "Dungeon"]
    attribute_map["Tower of Hera - Moldorm"] = ["Light World", "North Hyrule", "Death Mountain", "Tower of Hera", "Dungeon", "Boss"]
    attribute_map["Tower of Hera - Prize"] = ["Light World", "North Hyrule", "Death Mountain", "Tower of Hera", "Dungeon", "Prize"]

    #Dark World
    attribute_map["Superbunny Cave - Top"] = ["Dark World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Superbunny Cave - Bottom"] = ["Dark World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Hookshot Cave - Top Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Hookshot Cave - Top Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Hookshot Cave - Bottom Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Hookshot Cave - Bottom Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Group"]
    attribute_map["Spike Cave"] = ["Dark World", "North Hyrule", "Death Mountain"]
    attribute_map["Catfish"] = ["Dark World", "Northeast Hyrule"]
    attribute_map["Pyramid"] = ["Dark World", "Central Hyrule", "Pyramid"]
    attribute_map["Pyramid Fairy - Left"] = ["Dark World", "Central Hyrule", "Pyramid" "Group"]
    attribute_map["Pyramid Fairy - Right"] = ["Dark World", "Central Hyrule", "Pyramid" "Group"]
    attribute_map["Brewery"] = ["Dark World", "West Hyrule", "Village of Outcasts"]
    attribute_map["C-Shaped House"] = ["Dark World", "West Hyrule", "Village of Outcasts"]
    attribute_map["Chest Game"] = ["Dark World", "West Hyrule", "Village of Outcasts"]
    attribute_map["Hammer Pegs"] = ["Dark World", "Central Hyrule"]
    attribute_map["Bumper Cave"] = ["Dark World", "Northwest Hyrule"]
    attribute_map["Hype Cave - Top"] = ["Dark World", "South Hyrule", "Group"]
    attribute_map["Hype Cave - Middle Right"] = ["Dark World", "South Hyrule", "Group"]
    attribute_map["Hype Cave - Middle Left"] = ["Dark World", "South Hyrule", "Group"]
    attribute_map["Hype Cave - Bottom"] = ["Dark World", "South Hyrule", "Group"]
    attribute_map["Stumpy"] = ["Dark World", "Central Hyrule", "NPC"]
    attribute_map["Hype Cave - NPC"]  = ["Dark World", "South Hyrule", "Group", "NPC"]
    attribute_map["Digging Game"] = ["Dark World", "West Hyrule"]
    attribute_map["Mire Shed - Left"] = ["Dark World", "Southwest Hyrule", "Swamp"]
    attribute_map["Mire Shed - Right"] = ["Dark World", "Southwest Hyrule", "Swamp"]

    #Dark Palace
    attribute_map["Palace of Darkness - Shooter Room"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Big Key Chest"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - The Arena - Ledge"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - The Arena - Bridge"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Stalfos Basement"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Map Chest"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Big Chest"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Compass Chest"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Harmless Hellway"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Dark Basement - Left"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon", "Group"]
    attribute_map["Palace of Darkness - Dark Basement - Right"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon", "Group"]
    attribute_map["Palace of Darkness - Dark Maze - Top"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Dark Maze - Bottom"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon"]
    attribute_map["Palace of Darkness - Helmasaur King"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon", "Boss"]
    attribute_map["Palace of Darkness - Prize"] = ["Dark World", "East Hyrule", "Palace of Darkness", "Dungeon", "Prize"]

    #Swamp Palace
    attribute_map["Swamp Palace - Entrance"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon"]
    attribute_map["Swamp Palace - Big Chest"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon"]
    attribute_map["Swamp Palace - Big Key Chest"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon"]
    attribute_map["Swamp Palace - Map Chest"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon"]
    attribute_map["Swamp Palace - West Chest"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon"]
    attribute_map["Swamp Palace - Compass Chest"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon"]
    attribute_map["Swamp Palace - Flooded Room - Left"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon", "Group"]
    attribute_map["Swamp Palace - Flooded Room - Right"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon", "Group"]
    attribute_map["Swamp Palace - Waterfall Room"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon"]
    attribute_map["Swamp Palace - Arrghus"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon", "Boss"]
    attribute_map["Swamp Palace - Prize"] = ["Dark World", "South Hyrule", "Swamp Palace", "Dungeon", "Prize"]

    #Skull Woods 
    attribute_map["Skull Woods - Big Chest"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon"]
    attribute_map["Skull Woods - Big Key Chest"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon"]
    attribute_map["Skull Woods - Compass Chest"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon"]
    attribute_map["Skull Woods - Map Chest"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon"]
    attribute_map["Skull Woods - Bridge Room"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon"]
    attribute_map["Skull Woods - Pot Prison"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon"]
    attribute_map["Skull Woods - Pinball Room"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon"]
    attribute_map["Skull Woods - Mothula"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon", "Boss"]
    attribute_map["Skull Woods - Prize"] = ["Dark World", "NorthWest Hyrule", "Skull Woods", "Dungeon", "Prize"]

    #Thieves Town
    attribute_map["Thieves' Town - Attic"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Dungeon"]
    attribute_map["Thieves' Town - Big Key Chest"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Dungeon"]
    attribute_map["Thieves' Town - Map Chest"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Dungeon"]
    attribute_map["Thieves' Town - Compass Chest"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Dungeon"]
    attribute_map["Thieves' Town - Ambush Chest"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Dungeon"]
    attribute_map["Thieves' Town - Big Chest"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Dungeon"]
    attribute_map["Thieves' Town - Blind's Cell"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Dungeon"]
    attribute_map["Thieves' Town - Blind"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Boss"]
    attribute_map["Thieves' Town - Prize"] = ["Dark World", "West Hyrule", "Village of Outcasts", "Thieves' Town", "Prize"]

    #Ice Palace
    attribute_map["Ice Palace - Big Key Chest"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon"]
    attribute_map["Ice Palace - Compass Chest"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon"]
    attribute_map["Ice Palace - Map Chest"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon"]
    attribute_map["Ice Palace - Spike Room"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon"]
    attribute_map["Ice Palace - Freezor Chest"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon"]
    attribute_map["Ice Palace - Iced T Room"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon"]
    attribute_map["Ice Palace - Big Chest"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon"]
    attribute_map["Ice Palace - Kholdstare"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon", "Boss"]
    attribute_map["Ice Palace - Prize"] = ["Dark World", "Southeast Hyrule", "Ice Palace", "Dungeon", "Prize"]

    #Misery Mire
    attribute_map["Misery Mire - Big Chest"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon"]
    attribute_map["Misery Mire - Main Lobby"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon"]
    attribute_map["Misery Mire - Big Key Chest"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon"]
    attribute_map["Misery Mire - Compass Chest"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon"]
    attribute_map["Misery Mire - Bridge Chest"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon"]
    attribute_map["Misery Mire - Map Chest"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon"]
    attribute_map["Misery Mire - Spike Chest"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon"]
    attribute_map["Misery Mire - Vitreous"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon", "Boss"]
    attribute_map["Misery Mire - Prize"] = ["Dark World", "Southwest Hyrule", "Swamp", "Misery Mire", "Dungeon", "Prize"]

    #Turtle Rock
    attribute_map["Turtle Rock - Chain Chomps"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon"]
    attribute_map["Turtle Rock - Compass Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon"]
    attribute_map["Turtle Rock - Roller Room - Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Group"]
    attribute_map["Turtle Rock - Roller Room - Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Group"]
    attribute_map["Turtle Rock - Big Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon"]
    attribute_map["Turtle Rock - Big Key Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon"]
    attribute_map["Turtle Rock - Crystaroller Room"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon"]
    attribute_map["Turtle Rock - Eye Bridge - Bottom Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Group"]
    attribute_map["Turtle Rock - Eye Bridge - Bottom Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Group"]
    attribute_map["Turtle Rock - Eye Bridge - Top Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Group"]
    attribute_map["Turtle Rock - Eye Bridge - Top Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Group"]
    attribute_map["Turtle Rock - Trinexx"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Boss"]
    attribute_map["Turtle Rock - Prize"] = ["Dark World", "North Hyrule", "Death Mountain", "Turtle Rock", "Dungeon", "Prize"]

    #Ganons Tower
    attribute_map["Ganon's Tower - Bob's Torch"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - DMs Room - Top Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - DMs Room - Top Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - DMs Room - Bottom Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - DMs Room - Bottom Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Randomizer Room - Top Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Randomizer Room - Top Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Randomizer Room - Bottom Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Randomizer Room - Bottom Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Firesnake Room"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - Map Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - Big Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - Hope Room - Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Hope Room - Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Bob's Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - Tile Room"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - Compass Room - Top Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Compass Room - Top Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Compass Room - Bottom Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Compass Room - Bottom Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Big Key Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - Big Key Room - Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Big Key Room - Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Mini Helmasaur Room - Left"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Mini Helmasaur Room - Right"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon", "Group"]
    attribute_map["Ganon's Tower - Pre-Moldorm Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]
    attribute_map["Ganon's Tower - Moldorm Chest"] = ["Dark World", "North Hyrule", "Death Mountain", "Ganon's Tower", "Dungeon"]

    return attribute_map
